### ISSUE TITLE
Seeing LOADING Redis is loading the dataset in memory

### ISSUE THREAD

**Issue by ivanmarchenko83** [Namoshek/laravel-redis-sentinel#14]
This happens when one of sentinels pods is recreated and it starts loading stuff from other instances.

I would say this case is pretty much the same as when instance become READONLY. 
It should force reconnect to new master.
i.e. same logic as here:
https://github.com/Namoshek/laravel-redis-sentinel/blob/da8bb40f9ade0ee5c40500f5707a1627dba89023/src/Connections/PhpRedisSentinelConnection.php#L228 but for "LOADING Redis is loading the dataset in memory"

**Comment by Namoshek** [comment]
Interesting. Is it normal behavior of Redis Sentinel that it promotes a node if its not usable (yet)?

**Comment by ivanmarchenko83** [comment]
I don't think it is promoted as master at the time of connection attempt. Most probably it just returns LOADING, because it is **not even a  READONLY yet**. It would be logical. And this library just does not expect LOADING as a version of not usable connection.
At least I could not find any proof that it was promoted as master node.

**Comment by Namoshek** [comment]
Okay, I've looked into the Redis source code and it seems that `LOADING` is in fact interpreted as an acceptable status code to a `PING`, just like `PONG` and `MASTERDOWN` ([source](https://github.com/redis/redis/blob/51af17e3cf62cf77258c35509544a9b273327d2a/src/sentinel.c#L2793-L2835)). I find this somewhat counterintuitive and don't think Redis Sentinel should advertise an unready Redis instance, but I guess there might be good reasons to do so anyway.

I've created a PR with some changes in #16. It contains some logic we use nowadays with a different kind of Redis connector (we actually use KeyDB with multiple active-active master nodes). Please have a look and give me feedback if this looks good to you.

**Comment by ivanmarchenko83** [comment]
Looks good, thanks.
Really appriciate you looking into it!

**Comment by Namoshek** [comment]
Alright, release as `v0.2.1`. Please let me know if this solves your problem. :+1:

**Comment by ivanmarchenko83** [comment]
resolved in v0.2.1
