### ISSUE TITLE
Migrating from monospice/laravel-redis-sentinel-drivers library

### ISSUE THREAD

**Issue by devnicolas1** [Namoshek/laravel-redis-sentinel#18]
Hello! I'm currently migrating a project from monospice/laravel-redis-sentinel-drivers to this library, but I'm having a really hard time fully understanding how I should adapt all my configs. I would deeply appreciate any sort of help, if possible.

Currently, my `database.php` file looks like this:

```php
'redis' => [
        'retry_count'    => env('REDIS_RETRY_COUNT', 20),
        'retry_sleep_ms' => env('REDIS_RETRY_SLEEP_MS', 200),
        'client' => env('REDIS_CLIENT', 'phpredis-sentinel'),
        'options' => [
            'cluster' => env('REDIS_CLUSTER', 'redis'),
            'prefix' => env('REDIS_PREFIX', Str::slug(env('APP_NAME'), '_').'_database_'),
        ],

        'default' => [
            'password' => env('REDIS_BROADCAST_PASSWORD', $password),
            'port' => env('REDIS_BROADCAST_PORT', $port),
            'database' => env('REDIS_QUEUE_DATABASE', $database),
            'options' => [
                'prefix' => env('REDIS_PREFIX', Str::slug(env('APP_NAME'), '_').'_default_'),
            ],
            'sentinel_host' => env('REDIS_SENTINEL_HOST', $host),
            'sentinel_port' => (int) env('REDIS_SENTINEL_PORT', $port),
            'sentinel_service' => env('REDIS_SENTINEL_SERVICE', $service),
            'sentinel_timeout' => (float) env('REDIS_SENTINEL_TIMEOUT', 0.1),
            'sentinel_persistent' => env('REDIS_SENTINEL_PERSISTENT'),
            'sentinel_retry_interval' => env('REDIS_SENTINEL_RETRY_INTERVAL', 1000),
            'sentinel_read_timeout' => env('REDIS_SENTINEL_READ_TIMEOUT', 0),
            'sentinel_password' => env('REDIS_SENTINEL_PASSWORD'),
        ],

        'cache' => [
            'host' => env('REDIS_BROADCAST_HOST', $host),
            'password' => env('REDIS_BROADCAST_PASSWORD', $password),
            'port' => env('REDIS_BROADCAST_PORT', $port),
            'database' => env('REDIS_CACHE_DATABASE', $database),
            'sentinel_host' => env('REDIS_SENTINEL_HOST', $host),
            'sentinel_port' => (int) env('REDIS_SENTINEL_PORT', $port),
            'sentinel_service' => env('REDIS_SENTINEL_SERVICE', $service),
            'sentinel_timeout' => (float) env('REDIS_SENTINEL_TIMEOUT', 0.1),
            'sentinel_persistent' => env('REDIS_SENTINEL_PERSISTENT'),
            'sentinel_retry_interval' => env('REDIS_SENTINEL_RETRY_INTERVAL', 1000),
            'sentinel_read_timeout' => env('REDIS_SENTINEL_READ_TIMEOUT', 0),
            'sentinel_password' => env('REDIS_SENTINEL_PASSWORD'),
        ],
```
There also other entries (like `session`, `broadcasting`), but they are essentially the same as `cache`.

In my `cache.php` file, I have:
```php
        'redis' => [
            'driver' => 'redis',
            'connection' => 'cache',
        ],

        'phpredis-sentinel' => [
            'driver' => 'redis',
            'connection' => env(
                'CACHE_REDIS_SENTINEL_CONNECTION',
                env('CACHE_REDIS_CONNECTION', 'cache')
            ),
        ],
```
The relevant part of my `.env` is:
```env
REDIS_CLIENT=phpredis-sentinel
REDIS_CLUSTER=predis
REDIS_DRIVER=phpredis-sentinel
CACHE_DRIVER=phpredis-sentinel
```

Since the project is already running, I know things like the host, password, database and etc are correct. What is really confusing me, is how exactly I should add the new driver (`phpredis-sentinel`) into my configs. For instance, when we were still using the Monospice library, the `cache.php` file had:
```php
        'redis-sentinel' => [
            'driver' => 'redis-sentinel
            'connection' => env(
                'CACHE_REDIS_SENTINEL_CONNECTION',
                env('CACHE_REDIS_CONNECTION', 'cache')
            ),
        ],
```
The `.env` looked like:
```env
REDIS_CLIENT=predis
REDIS_CLUSTER=predis
REDIS_DRIVER=redis-sentinel
CACHE_DRIVER=redis-sentinel
```

When switching libraries, I first thought that I'd have to switch all my references of `redis-sentinel` as a driver to `phpredis-sentinel`, while also defining the client and the other `sentinel_*` variables mentioned in the README. Thing is, in my `cache.php`, when I try to use `'driver' => 'phpredis-sentinel`, I receive the error `Driver [phpredis-sentinel] is not supported`. The only driver I managed to make work, is `redis`.

So, my main question here is: is defining the client in `database.php` enough, or should I actually be able to manually define the drivers in `cache.php` and the other files like that (`session.php`, etc)? If the driver should be defined (and not be simply `redis`), can you spot any possible reason for why Laravel is returning a `not supported` message? Library is installed, of course.

Since the README doesn't mention any special configuration for files like `cache.php` or the `.env`, I really don't know exactly how should I "simplify" all the past configs to adapt it to the new library. Should I really just stick with `redis` as a driver for everything and the `phpredis-sentinel` client defined in `database.php` will do all the magic? 

I will gladly send any other details that might be needed, and even add some more content to the README if you judge it might be interesting for people who might be in a spot like mine.

Regardless of all that, thanks for the awesome library! :)

**Comment by Namoshek** [comment]
What Laravel version are you running on?

**Comment by devnicolas1** [comment]
Currently trying on Laravel 9 since its the stable and working version of the project, but the plan is to put it into Laravel 10 right after making it work. Reason for this is that, since the project is already stable on Laravel 9, we thought it would be easier to make it work first, and then upgrading to 10.

**Comment by Namoshek** [comment]
Ok, I see - your upgrade strategy should be no problem at all.

**Regarding the configuration:**
There are five config files that normally - in one way or another - define or reference the Redis configuration:
- `config/database.php`
- `config/broadcasting.php`
- `config/cache.php`
- `config/session.php`
- `config/queue.php`

The first one, `config/database.php`, configures the actual Redis connections, while the other four only reference the connections of the former. So `CACHE_DRIVER=phpredis-sentinel` is wrong and should simply be `redis` (same for all other occurrences). The only reference to `phpredis-sentinel` should be the `client` in `config/database.php`.

What I also find odd about your configuration is the `REDIS_CLUSTER=predis` part. The package is entirely incompatible with `predis` (since `predis` supports Redis Sentinel out of the box already, as far as I know). Maybe remove this option all-together...

**Comment by Namoshek** [comment]
The operation timed out error sounds like a firewall issue to me. Are you sure that you are able to connect from the machine you are testing this on? Maybe run `telnet <ip> <port>` for both the Redis Sentinel and Redis ports and all IPs.

**Comment by Namoshek** [comment]
Maybe as a little more help, here the configuration we've been using successfully.

_config/database.php:_
```php
return [

    'redis' => [

        'client' => 'phpredis-sentinel',

        'default' => [
            'sentinel_host' => env('REDIS_SENTINEL_HOST', '127.0.0.1'),
            'sentinel_port' => intval(env('REDIS_SENTINEL_PORT', 26379)),
            'sentinel_password' => env('REDIS_SENTINEL_PASSWORD'),
            'sentinel_service' => env('REDIS_SENTINEL_SERVICE', 'mymaster'),
            'sentinel_timeout' => env('REDIS_SENTINEL_TIMEOUT', 0),
            'sentinel_persistent' => env('REDIS_SENTINEL_PERSISTENT'),
            'sentinel_retry_interval' => env('REDIS_SENTINEL_RETRY_INTERVAL', 0),
            'sentinel_read_timeout' => env('REDIS_SENTINEL_READ_TIMEOUT', 0),
            'password' => env('REDIS_PASSWORD'),
            'database' => 0,
        ],
    ]
];
```

**Comment by devnicolas1** [comment]
To conclude all of this: although I couldn't make this library work, I do managed to find a workaround in our project that solved our problems pretty decently. Regardless of that, thank you for all the help! Really appreciate it :)
