### ISSUE TITLE
RedisSentinel::__construct() expects at most 1 argument, 6 given

### ISSUE THREAD

**Issue by DevHeaven** [Namoshek/laravel-redis-sentinel#22]
My app has been running fine for the last 12 Months. Since a few days I'm getting errors as soon as I use Redis::

For example , running this command in Laravel : **Redis::command('SELECT',[6]);**
The error is below : 

`object(ArgumentCountError)#1441 (7) {
  ["message":protected]=>
  string(64) "RedisSentinel::__construct() expects at most 1 argument, 6 given"
  ["string":"Error":private]=>
  string(0) ""
  ["code":protected]=>
  int(0)
  ["file":protected]=>
  string(92) "/var/www/vendor/namoshek/laravel-redis-sentinel/src/Connectors/PhpRedisSentinelConnector.php"
  ["line":protected]=>
  int(99)
  ["trace":"Error":private]=>
  array(35) {
    [0]=>
    array(6) {
      ["file"]=>
      string(92) "/var/www/vendor/namoshek/laravel-redis-sentinel/src/Connectors/PhpRedisSentinelConnector.php"
      ["line"]=>
      int(99)
      ["function"]=>
      string(11) "__construct"
      ["class"]=>
      string(13) "RedisSentinel"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(6) {
        [0]=>
        string(42) "redis-***redacted****"
        [1]=>
        int(26379)
        [2]=>
        int(0)
        [3]=>
        bool(false)
        [4]=>
        int(0)
        [5]=>
        int(0)
      }
    }
`

**Comment by Namoshek** [comment]
What version of this package are you using? There have been breaking changes with the `phpredis` PHP extension in version `6.0` and in [release `v0.3.0`](https://github.com/Namoshek/laravel-redis-sentinel/releases/tag/v0.3.0) a fix for this has already been shipped.
