### ISSUE TITLE
PhpRedisConnector is used instead of PhpRedisSentinelConnector

### ISSUE THREAD

**Issue by LyKos4** [Namoshek/laravel-redis-sentinel#32]
By using below definition for default and expecting it to use the PhpRedisSentinelConnector, I am getting error 
In PhpRedisConnector.php line 232: Undefined array key "host" , so it seems that the new connector is not used.
Is there anything additional that needs to be set up? 

        'default' => [
            'host' => env('REDIS_SENTINEL_HOST', '127.0.0.1'),
            'port' => env('REDIS_SENTINEL_PORT', 26379),
            'sentinel_service' => env('REDIS_SENTINEL_SERVICE', 'mymaster'),
            'sentinel_timeout' => env('REDIS_SENTINEL_TIMEOUT', 0),
            'sentinel_persistent' => env('REDIS_SENTINEL_PERSISTENT'),
            'sentinel_retry_interval' => env('REDIS_SENTINEL_RETRY_INTERVAL', 0),
            'sentinel_read_timeout' => env('REDIS_SENTINEL_READ_TIMEOUT', 0),
            'sentinel_username' => env('REDIS_SENTINEL_USERNAME'),
            'sentinel_password' => env('REDIS_SENTINEL_PASSWORD'),
            'password' => env('REDIS_PASSWORD'),
            'database' => 0,
            'client' => 'phpredis-sentinel',
        ],

I use a separate single instance for session that continues to use the phpredis client

        'session' => [
            'url'      => env('REDIS_SESSION_URL', env('URL')),
            'host'     => env('REDIS_SESSION_HOST', env('HOST', '127.0.0.1')),
            'password' => env('REDIS_SESSION_PASSWORD', env('PASSWORD', null)),
            'port'     => $redis_port,
            'database' =>  env('DATABASE', 0),
            'client' => 'phpredis',
        ]

**Comment by LyKos4** [comment]
seems that if client is placed above session and default and not inside their blocks it works, so using different clients will not be so straight forward.

**Comment by Namoshek** [comment]
Yes, that's not easy to achieve. The `RedisManager` is itself instantiated with a single driver that is used for all connections:

https://github.com/laravel/framework/blob/79c9874700427e0e469fb3f56c5f072342263e73/src/Illuminate/Redis/RedisManager.php#L69-L74

You could in theory inject a custom, second `RedisManager` with a different driver into the service container. However, using this other connection manager in other parts of the framework (e.g. cache) would be very challenging in my opinion.

**Comment by LyKos4** [comment]
After setting universal client as seen below:
    'redis' => [
        'client' => env('REDIS_CLIENT', 'phpredis-sentinel'),

        'default' => [
            'sentinel_host' => env('REDIS_SENTINEL_HOST', '127.0.0.1'),
            'sentinel_port' => (int) env('REDIS_SENTINEL_PORT', 26379),
            'sentinel_service' => env('REDIS_SENTINEL_SERVICE', 'mymaster'),
            'sentinel_timeout' => env('REDIS_SENTINEL_TIMEOUT', 0),
            'sentinel_persistent' => env('REDIS_SENTINEL_PERSISTENT'),
            'sentinel_retry_interval' => env('REDIS_SENTINEL_RETRY_INTERVAL', 0),
            'sentinel_read_timeout' => env('REDIS_SENTINEL_READ_TIMEOUT', 0),
            'sentinel_username' => env('REDIS_SENTINEL_USERNAME'),
            'sentinel_password' => env('REDIS_SENTINEL_PASSWORD'),
            'password' => env('REDIS_PASSWORD'),
            'database' => 0,
        ],
        ....
  ]
I am getting this error:  
ERROR:  In PhpRedisConnector.php line 161:
php_network_getaddresses: getaddrinfo for redis-0.redis failed: Name or service not known

Why PhpRedisConnector is used while I have defined the phpredis-sentinel client?
Shouldn't only the  PhpRedisSentinelConnection.php be used?

**Comment by Namoshek** [comment]
Looks like your sentinels return incomplete FQDNs, maybe check their config and add the `.svc.cluster.local` part.

`PhpRedisConnection` being called is fine. `PhpRedisSentinelConnection` is just a wrapper around the built-in driver that first resolves the Redis address from the Sentinels, then falls back to the default implementation using that address.
