### ISSUE TITLE
Laravel Horizon support

### ISSUE THREAD

**Issue by belazz** [Namoshek/laravel-redis-sentinel#34]
Hello,

I would like to migrate from monospice's predis sentinel package to your package, but the only thing stopping me is how will it handle Laravel Horizon? Did you try your package together with Horizon? There are some workarounds that need to be configured for predis drivers and it feels like the same should be done for this package, though there are less options available.

We are using Laravel 9 for most of our projects, and 10 for newer ones

**Comment by Namoshek** [comment]
Horizon uses whatever Redis connection you configure. So it will use the Sentinel driver with no problem.

However, I'm not using Horizon anymore and also not this Sentinel driver (in favour of something entirely different), so I can't give any guarantees. Make sure to test your stuff thoroughly.
