### ISSUE TITLE
TLS/SSL Support

### ISSUE THREAD

**Issue by DevHeaven** [Namoshek/laravel-redis-sentinel#35]
Hello

I believe this package does not yet support connecting to Sentinel over TLS/SSL ?
Are you considering implementation ?
If it does exist, could you point me to where the configuration is done ?

Much appreciated

**Comment by Namoshek** [comment]
Based on the [sentinel documentation of `phpredis/phpredis`](https://github.com/phpredis/phpredis/blob/0fe45d24d4d8c115a5b52846be072ecb9bb43329/sentinel.md), I'm not sure this is even supported?!

**Comment by DevHeaven** [comment]
I'm afraid you are right :'( 
Thanks for the quick response!

Now to find a solution, because our production clusters have mandatory TLS

**Comment by DevHeaven** [comment]
But here I see a TLS commit : https://github.com/phpredis/phpredis/issues/2114

**Comment by Namoshek** [comment]
Interesting find, maybe it is possible. This should mostly affect the following part of the code:

https://github.com/Namoshek/laravel-redis-sentinel/blob/3d6fad1c4d07fe4098fd2af260697ebe86c63304/src/Connectors/PhpRedisSentinelConnector.php#L84-L129

However, the way the phpredis library works, you can only pass the object when its actually being used. So the workaround of L128 needs to be used for this as well, making the code a bit bulky. If you want to give it a try, feel free. Otherwise I'll see when I find the time.

**Comment by BramVanDaele** [comment]
By the statement "workaround L128" , you mean the fact that RedisSentinel doesn't accept more then 6 function parameters ?
Not sure why it's not complaining about the $auth .... or I'm misunderstanding you.

**Comment by Namoshek** [comment]
Sorry if that wasn't very helpful. I'm not sure if the SSL context works similar to the auth options. With the auth options, the `RedisSentinel` class complains if you pass them as `null`. Instead, the parameter needs to be omitted entirely. Which, to be honest, is kinda problematic if you need to pass an argument after it... I guess that needs some fiddling and testing.

**Comment by BramVanDaele** [comment]
Hmmm, if RedisSentinel indeed requires it not to be null, then it would be impossible to provide any following parameters without the auth option (given we can't rewrite the function declaration ourselves).

One could argue that if you want to secure your connection with TLS , you would not want to use NOAUTH.
So , if TLS is to be used AUTH is mandatory. However, that limits the functionality for cases where this is required.

Could you work out an example of connecting with both AUTH and TLS/SSL Context ?

**Comment by BramVanDaele** [comment]
By the way ... coincidence (5 hours ago) :-) : https://github.com/phpredis/phpredis/commit/8144db374338006a316beb11549f37926bd40c5d

**Comment by BramVanDaele** [comment]
Apparantly the latest version 6.1 , released 4 weeks ago includes support for TLS/SSL : https://github.com/phpredis/phpredis/commit/f2bb2cdb5a8cc770d22b6d516e230d2cf544929b#diff-16398f4eda044362a02548e382f2ec7dfd1aae291be015c075d2409928ddf295R11

**Comment by BramVanDaele** [comment]
I've pulled the branch and added it to my local repos. I changed the configuration as follows : 

`    'redis' => [
        'client' => 'phpredis-sentinel',

        'redis_with_tls' => [
            'sentinel_host' => 'tls://my_sentinel_host',
            'sentinel_port' => 26379,
            'sentinel_service' => 'mymaster',
            'sentinel_timeout' => 0,
            'sentinel_persistent' => false,
            'sentinel_retry_interval' => 0,
            'sentinel_read_timeout' => 0,
            'sentinel_username' => 'my_sentinel_username',
            'sentinel_password' => 'my_sentinel_password',
            'sentinel_ssl' => [
                'verify_peer' => false,
                'verify_peer_name' => false,
            ],
            'username' => 'my_redis_username',
            'password' => 'my_redis_password',
            'database' => 1,
        ],
    ]
`

When using Redis::connection('redis_with_tls') , I get the error : 

**read error on connection to 10.153.64.21:6379**   (one of the Redis nodes)

**Comment by Namoshek** [comment]
That's interesting because it seems that the Redis instance resolution through Sentinel worked at this point. Is your Sentinel configured to resolve non-SSL connections or should it return the Redis address with an SSL port?

Anyway, you might want to add `'scheme'' => 'tls'` to your config, it may be used by the underlying `PhpRedisConnector` when establishing the actual connection.

**Comment by BramVanDaele** [comment]
I was indeed just testing adding 'scheme' => 'tls'

Strangely I get back :
**Redis::connect(): Peer certificate CN=`redacted_redis_node_name' did not match expected CN=`10.153.64.21'**

Even though I have "verify_peer" set to false.

So yes, indeed , it looks like the resoliution to Redis Sentinel instance is fine, but the connection afterwards fails.
I'll check with our SRE on how our Redis Sentinel is configured and get back to you.

**Comment by Namoshek** [comment]
I think if you add your SSL options as `context` option, it adds them as SSL context for the Redis connection itself:

https://github.com/laravel/framework/blob/0be1995727a7c9341d13a08253a12140b8fc84fd/src/Illuminate/Redis/Connectors/PhpRedisConnector.php#L155-L157

**Comment by BramVanDaele** [comment]
I've got it working ! The SSL context needs to be inside streaming .
Just to be clear, the full config that is working with AUTH and TLS/SSL

`
    'redis' => [

        'client' => 'phpredis-sentinel',

        'redis_with_tls' => [
            'sentinel_host' => 'tls://sentinel_host',
            'sentinel_port' => 26379,
            'sentinel_service' => 'mymaster',
            'sentinel_timeout' => 0,
            'sentinel_persistent' => false,
            'sentinel_retry_interval' => 0,
            'sentinel_read_timeout' => 0,
            'sentinel_username' => 'sentinel_username',
            'sentinel_password' => 'sentinel_password',
            'sentinel_ssl' => [
                'verify_peer' => false,
                'verify_peer_name' => false,
            ],
            'options' => [
                'context' => [
                    'stream' => [
                        'verify_peer' => false,
                        'verify_peer_name' => false,
                    ]
                ]
            ],
            'scheme' => 'tls',
            'username' => 'redis_username',
            'password' => 'redis_password',
            'database' => 1,
        ],
    ]
`

**Comment by BramVanDaele** [comment]
Awesome , I truly appreciate all the efforts !
Will be pulling the newest version and doing some tests tomorrow.
