### ISSUE TITLE
How to configure multiple sentinel hosts?

### ISSUE THREAD

**Issue by Alhubing** [Namoshek/laravel-redis-sentinel#41]
Hello.
Common sentinel configurations have at least 3 sentinel nodes, but, according to the docs, the config file accepts only one sentinel host parameter.
Can i provide more than one sentinel connections?

Edit: Nevermind, i just saw there is already an issue for this topic.

**Comment by Namoshek** [comment]
It's not necessarily an issue to add support for an array of Sentinel hosts. However, it is quite tricky to implement a failsafe logic that selects a working host in terms of timeouts and other things. Handling this kind of issue at the infrastructure level just makes more sense, so I advise to go this path if possible.
