### ISSUE TITLE
Cannot use env variables with numeric values

### ISSUE THREAD

**Issue by Alhubing** [Namoshek/laravel-redis-sentinel#42]
Hello!
Ive testing a little and realize that configuration parameters does not work with env varibles for numeric values.

REDIS_SENTINEL_PORT
REDIS_SENTINEL_TIMEOUT
REDIS_SENTINEL_RETRY_INTERVAL
REDIS_SENTINEL_READ_TIMEOUT

Laravel parse these values as string so it fails when trying to create the connection because RedisSentinel class expects numeric values for these options.

Casting these values should be enough to make it work.

**Comment by Namoshek** [comment]
Good catch, I think this behavior has changed over time through the introduction of types in the framework. I've updated the config snippet in the README.
